#!/bin/bash

# Load Resources
xrdb -merge .Xresources

# Start udiskie for external media
udiskie &

# Configure monitor layout with arandr
~/.screenlayout/main.sh

# Set wallpaper
feh --bg-scale /home/llamicron/usr/img/backgrounds/flowers-min.png

# Set default terminal to alacritty
terminal = "~/.cargo/bin/alacritty"

# Fire up apps
xscreensaver -no-splash &
if [ -x /usr/bin/nm-applet ]; then
	nm-applet --sm-disable &
fu

exec xmonad
