% Custom math symbols


% used a shitton in linear algebra
% \R gets you the fancy real numbers R
\newcommand{\R}{\textrm{I\!R}}
\newcommand{\Rn}{\R^n}
% Also \Poly for set of all polynomials
\newcommand{\Poly}{\textrm{I\!P}}
% Words in math, like rank A or Span{...}.
% \rank A = \text{rank } A
\newcommand{\Span}[1]{\text{Span}\left\{ #1 \right\}}
\newcommand{\rank}{\text{rank }}
\newcommand{\nullity}{\text{nullity }}
\newcommand{\Col}{\text{Col }}
\newcommand{\Row}{\text{Row }}
\newcommand{\Nul}{\text{Nul }}


% A set of vectors from 1, .., n
% {b_1,···,b_n}, with vector arrows
% Example
%   $B = \nvectors{b}$
\newcommand{\nvectors}[1]{ \left\{ \vec{#1_1}, \cdots, \vec{#1_n} \right\} }

