% For code listings
\usepackage{listings}

% For code listings
% \usepackage[section]{minted}

% For the courier font
\usepackage{courier}
% not sure what i use these for honestly, too lazy to figure out
% \usepackage{graphicx}
% \usepackage{gensymb}
% A few math tools that I sometimes use
\usepackage{mathtools}
% For circuit symbols (used in PHYS 1444 and probably later)
% \usepackage{circuitikz}
% This is just for tables
\usepackage{tabularx}
% The magical math package, used for a lot of shit
\usepackage{amsmath}
% More math symbols
\usepackage{amssymb}
% For framed boxes
% \begin{framed}
% example
% \end{framed}
\usepackage{framed}
% For the header bar
\usepackage{fancyhdr}
% For coordinate system
% Uncomment if you need this, its big i think
% \usepackage{tkz-euclide}
% This package is used for drawing node graphs
% Uncomment if you need it. See the guide here:
% https://www.baeldung.com/cs/latex-drawing-graphs
% \usepackage{tikz}
% This one is for CSE 2315
% This was for the way our prof wanted homework formatted.
% Steps needed to be tabbed to a certain width.
% \usepackage{tabto}
% I think this one makes everything \noindent
\usepackage{parskip}
% Styling links
% \href{https://youtube.com}{example}
\usepackage{hyperref}
% Colored boxes
\usepackage{tcolorbox}
% Enumeration
% \usepackage{enumitem}
% Fancy ornaments
\usepackage[object=vectorian]{pgfornament}
% For current date and time
\usepackage{datetime2}
% For setting the page size
\usepackage{geometry}
% For defining colors
\usepackage{xcolor}